version: '2'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    build: .
    command: foreman start -f Procfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - 'postgres'

volumes:
  postgres: