version: '2'
services:
  postgres:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    build: .
    env_file: web.env
    command: bash -c "rm -rf /app/tmp/pids/server.pid && foreman start -f Procfile.dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - 'postgres'
volumes:
  postgres:
