development:
  hosts:
    - 127.0.0.1
  port: 9042
  keyspace: engagement_dev
  replication:
    class: SimpleStrategy
    replication_factor: 1

test:
  hosts:
    - 127.0.0.1
  port: 9042
  keyspace: engagement_test
  replication:
    class: 'SimpleStrategy'
    replication_factor: 1

production:
  hosts:
    - 'cass1.my_app.biz'
    - 'cass2.my_app.biz'
    - 'cass3.my_app.biz'
  port: 9042
  keyspace: engagement_production
  username: nick
  password: password1
  replication:
    class: SimpleStrategy
    replication_factor: 1
